### ISSUE TITLE
ConnectionError: Couldn't reach 'results/dataset' on the Hub (ConnectionError)

### ISSUE THREAD

**Issue by dahaigui** [songlab-cal/gpn#12]
While using this GPN software, I encountered some issues, outlined as follows.

My command line is `python -m gpn.ss.run_mlm --do_train --do_eval --fp16 --prediction_loss_only True --remove_unused_columns False --dataset_name results/dataset --tokenizer_name gonzalobenegas/tokenizer-dna-mlm --soft_masked_loss_weight_train 0.1 --soft_masked_loss_weight_evaluation 0.0 --weight_decay 0.01 --optim adamw_torch --dataloader_num_workers 40 --seed 42 --save_strategy steps --save_steps 10000 --evaluation_strategy steps --eval_steps 10000 --logging_steps 10000 --max_steps 120000 --warmup_steps 1000 --learning_rate 1e-3 --lr_scheduler_type constant_with_warmup --run_name chenhx_B9008 --output_dir B9008_test --model_type ConvNet --per_device_train_batch_size 512 --per_device_eval_batch_size 512 --gradient_accumulation_steps 1`

After running for a while, an error occurred. How should I address this issue?

11/29/2023 03:16:17 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 4distributed training: True, 16-bits training: True
/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/datasets/load.py:2088: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
Traceback (most recent call last):
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chenhx/software/gpn/gpn/ss/run_mlm.py", line 564, in <module>
    main()
  File "/home/chenhx/software/gpn/gpn/ss/run_mlm.py", line 365, in main
    raw_datasets = load_dataset(
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/datasets/load.py", line 2128, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/datasets/load.py", line 1814, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/datasets/load.py", line 1511, in dataset_module_factory
    raise e1 from None
  File "/home/chenhx/miniconda3/envs/GPN/lib/python3.8/site-packages/datasets/load.py", line 1467, in dataset_module_factory
    raise ConnectionError(f"Couldn't reach '{path}' on the Hub ({type(e).__name__})")
ConnectionError: Couldn't reach 'results/dataset' on the Hub (ConnectionError)

**Comment by dahaigui** [comment]
I think I know what the problem is. My datasets path is not correctly specified.

**Comment by gonzalobenegas** [comment]
That's probably the case. As a quick note, `dataset_name` will be searched both locally and on the Huggingface Hub.
